import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, test } from 'vitest';

import { compileExportFixture, EXPORT_FIXTURES } from '../fixtures/export-fixture-definitions.mjs';

// Drift detector: tests/fixtures/exports/*.html are committed files, generated by
// scripts/generate-export-fixtures.mjs, that back both a manual test-page index
// (tests/fixtures/exports/index.html) and the automated tests/e2e/exported-fixtures.spec.js.
// If someone changes a component's generateHTML/generateCSS/generateJS and forgets to
// regenerate the fixture, this test fails loudly instead of the fixture silently going
// stale (still "passing" its own e2e checks, just not representing current output).
const fixturesDir = join(dirname(fileURLToPath(import.meta.url)), '..', 'fixtures', 'exports');

describe('export fixtures are in sync with the current export pipeline', () => {
  test.each(EXPORT_FIXTURES)('$filename matches a fresh compile of $componentId', async ({ componentId, filename }) => {
    const committed = await readFile(join(fixturesDir, filename), 'utf8');
    const fresh = compileExportFixture(componentId);
    expect(committed, `tests/fixtures/exports/${filename} is stale — run "npm run fixtures:exports" and commit the result`).toBe(fresh);
  });
});
